use std::collections::HashMap;
use std::net::SocketAddr;
use std::sync::Arc;
use std::time::Duration;

use bridge::core::config::{Config, ManagedConfig, ProxyConfig, UdpServiceConfig};
use proxy::core::enums::ProxyMode;
use proxy::managed::{
    generate_traefik_config, is_local_route, sanitize_traefik_name, sync_dynamic_config,
    traefik_config_to_yaml,
};
use proxy::{Proxy, ShutdownCoordinator};
use registry::{DomainRegistry, Node, Route, RoutingPreference};

#[test]
fn test_sanitize_traefik_name_and_rules() {
    assert_eq!(sanitize_traefik_name("app.example.com"), "bridge-app-example-com");
    assert_eq!(sanitize_traefik_name("coolify.test"), "bridge-coolify-test");
    assert_eq!(sanitize_traefik_name("api_v1.sub-domain.org"), "bridge-api_v1-sub-domain-org");
    assert_eq!(sanitize_traefik_name(""), "bridge-default");
}

#[test]
fn test_is_local_route_filter() {
    assert!(is_local_route("self", "vm-01"));
    assert!(is_local_route("vm-01", "vm-01"));
    assert!(!is_local_route("vm-02", "vm-01"));
    assert!(!is_local_route("vm-03", "self"));
}

#[test]
fn test_traefik_dynamic_config_generation_and_yaml() {
    let mut routes = HashMap::new();

    // Local route: should be skipped
    let local_node = Node::new("self", "127.0.0.1:80".parse().unwrap());
    routes.insert(
        "local.test".to_string(),
        Route::new(Some("127.0.0.1:8000".parse().unwrap()), local_node),
    );

    // Remote route 1: HTTP on custom port 3000
    let remote_node_1 = Node::new("vm-02", "10.8.0.2:3000".parse().unwrap());
    routes.insert(
        "app.example.com".to_string(),
        Route::new(None, remote_node_1),
    );

    // Remote route 2: HTTPS on port 443
    let remote_node_2 = Node::new("vm-03", "10.8.0.3:443".parse().unwrap());
    routes.insert(
        "secure.example.com".to_string(),
        Route::new(None, remote_node_2),
    );

    let registry = DomainRegistry::with_routes(routes);
    let managed_cfg = ManagedConfig::default()
        .with_local_node_id("self")
        .with_entrypoints(vec!["websecure".to_string()])
        .with_cert_resolver(Some("letsencrypt".to_string()));

    let traefik_config = generate_traefik_config(&registry, RoutingPreference::Mesh, &managed_cfg);

    // Local route must not be present
    assert!(!traefik_config.http.routers.contains_key("bridge-local-test"));
    assert!(!traefik_config.http.services.contains_key("bridge-local-test"));

    // Remote route 1: app.example.com
    let router1 = traefik_config.http.routers.get("bridge-app-example-com").unwrap();
    assert_eq!(router1.rule, "Host(`app.example.com`)");
    assert_eq!(router1.service, "bridge-app-example-com");
    assert_eq!(router1.entry_points, vec!["websecure"]);
    assert_eq!(
        router1.tls.as_ref().unwrap().cert_resolver.as_deref(),
        Some("letsencrypt")
    );

    let svc1 = traefik_config.http.services.get("bridge-app-example-com").unwrap();
    assert_eq!(svc1.load_balancer.servers.len(), 1);
    assert_eq!(svc1.load_balancer.servers[0].url, "http://10.8.0.2:3000");

    // Remote route 2: secure.example.com (port 443 -> https scheme)
    let router2 = traefik_config.http.routers.get("bridge-secure-example-com").unwrap();
    assert_eq!(router2.rule, "Host(`secure.example.com`)");
    let svc2 = traefik_config.http.services.get("bridge-secure-example-com").unwrap();
    assert_eq!(svc2.load_balancer.servers[0].url, "https://10.8.0.3:443");

    // Serialize to YAML and verify structure
    let yaml = traefik_config_to_yaml(&traefik_config).expect("failed to serialize YAML");
    assert!(yaml.contains("# Auto-generated by Bridge daemon in Managed mode"));
    assert!(yaml.contains("Host(`app.example.com`)"));
    assert!(yaml.contains("url: http://10.8.0.2:3000"));
    assert!(yaml.contains("url: https://10.8.0.3:443"));
    assert!(yaml.contains("certResolver: letsencrypt"));
    assert!(yaml.contains("websecure"));
}

#[test]
fn test_all_local_routes_generate_empty_traefik_config() {
    let mut routes = HashMap::new();
    let local_node = Node::new("vm-01", "127.0.0.1:80".parse().unwrap());
    routes.insert("app1.test".to_string(), Route::new(None, local_node.clone()));
    routes.insert("app2.test".to_string(), Route::new(None, local_node));

    let registry = DomainRegistry::with_routes(routes);
    let managed_cfg = ManagedConfig::default().with_local_node_id("vm-01");

    let traefik_config = generate_traefik_config(&registry, RoutingPreference::Mesh, &managed_cfg);
    assert!(traefik_config.http.is_empty());
    assert!(traefik_config.http.routers.is_empty());
    assert!(traefik_config.http.services.is_empty());

    let yaml = traefik_config_to_yaml(&traefik_config).unwrap();
    assert!(yaml.contains("http: {}"));
}

#[test]
fn test_routing_preference_direct_vs_mesh_in_managed_config() {
    let mut routes = HashMap::new();
    let multi_node = Node::new("vm-remote", "10.0.0.1:80".parse().unwrap())
        .with_mesh_address("10.8.0.4:3000".parse().unwrap())
        .with_direct_address("198.51.100.4:3000".parse().unwrap());

    routes.insert("api.mesh.test".to_string(), Route::new(None, multi_node.clone()));

    let registry = DomainRegistry::with_routes(routes);
    let managed_cfg = ManagedConfig::default();

    // Default or Mesh preference -> resolves mesh_address 10.8.0.4:3000
    let config_mesh = generate_traefik_config(&registry, RoutingPreference::Mesh, &managed_cfg);
    let svc_mesh = config_mesh.http.services.get("bridge-api-mesh-test").unwrap();
    assert_eq!(svc_mesh.load_balancer.servers[0].url, "http://10.8.0.4:3000");

    // Direct preference -> resolves direct_address 198.51.100.4:3000
    let config_direct = generate_traefik_config(&registry, RoutingPreference::Direct, &managed_cfg);
    let svc_direct = config_direct.http.services.get("bridge-api-mesh-test").unwrap();
    assert_eq!(svc_direct.load_balancer.servers[0].url, "http://198.51.100.4:3000");
}

#[test]
fn test_atomic_file_sync_and_change_detection() {
    let temp_dir = std::env::temp_dir().join(format!("bridge-traefik-test-{}", std::process::id()));
    let config_file = temp_dir.join("dynamic").join("bridge.yaml");

    let mut routes = HashMap::new();
    let node = Node::new("vm-02", "10.8.0.2:8080".parse().unwrap());
    routes.insert("initial.test".to_string(), Route::new(None, node.clone()));

    let registry = DomainRegistry::with_routes(routes);
    let managed_cfg = ManagedConfig::new(&config_file)
        .with_local_node_id("self")
        .with_cert_resolver(Some("letsencrypt".to_string()));

    // 1. Initial sync: file is written
    let updated1 = sync_dynamic_config(&managed_cfg, &registry, RoutingPreference::Mesh)
        .expect("initial sync failed");
    assert!(updated1);
    assert!(config_file.exists());
    let content1 = std::fs::read_to_string(&config_file).unwrap();
    assert!(content1.contains("Host(`initial.test`)"));
    assert!(content1.contains("http://10.8.0.2:8080"));

    // 2. Unchanged sync: returns false, file content untouched
    let updated2 = sync_dynamic_config(&managed_cfg, &registry, RoutingPreference::Mesh)
        .expect("second sync failed");
    assert!(!updated2);

    // 3. Insert new route into registry and sync: returns true, file updated
    registry.insert(
        "runtime-added.test".to_string(),
        Route::new(None, Node::new("vm-03", "10.8.0.3:9000".parse().unwrap())),
    );

    let updated3 = sync_dynamic_config(&managed_cfg, &registry, RoutingPreference::Mesh)
        .expect("third sync failed");
    assert!(updated3);
    let content3 = std::fs::read_to_string(&config_file).unwrap();
    assert!(content3.contains("Host(`initial.test`)"));
    assert!(content3.contains("Host(`runtime-added.test`)"));
    assert!(content3.contains("http://10.8.0.3:9000"));

    // Clean up
    let _ = std::fs::remove_dir_all(&temp_dir);
}

#[tokio::test]
async fn test_proxy_run_managed_mode_lifecycle_and_shutdown() {
    let temp_dir = std::env::temp_dir().join(format!("bridge-managed-run-{}", std::process::id()));
    let config_file = temp_dir.join("bridge-traefik.yaml");
    let state_file = temp_dir.join("bridge-state.json");

    let mut routes = HashMap::new();
    let remote_node = Node::new("vm-remote", "10.8.0.99:3000".parse().unwrap());
    routes.insert("fleet.test".to_string(), Route::new(None, remote_node));

    let registry = Arc::new(DomainRegistry::with_routes(routes));

    let mut proxy_cfg = ProxyConfig::default();
    proxy_cfg.mode = ProxyMode::Managed;
    proxy_cfg.managed = ManagedConfig::new(&config_file)
        .with_local_node_id("self")
        .with_sync_interval(Duration::from_millis(50));

    let proxy = Arc::new(Proxy::new(Arc::new(proxy_cfg), registry.clone()));
    let mut coordinator = ShutdownCoordinator::new(Some(state_file.clone()));

    // Run proxy with coordinator in background task
    let proxy_clone = proxy.clone();
    let runner_handle = tokio::spawn(async move {
        proxy_clone.run_with_coordinator(&mut coordinator).await
    });

    // Wait briefly for initial sync to flush to disk
    tokio::time::sleep(Duration::from_millis(150)).await;

    // Verify dynamic Traefik file was generated on disk
    assert!(config_file.exists());
    let file_content = std::fs::read_to_string(&config_file).unwrap();
    assert!(file_content.contains("Host(`fleet.test`)"));
    assert!(file_content.contains("http://10.8.0.99:3000"));

    // In Managed mode, Bridge does NOT bind TCP ports 80/443.
    // Verify an arbitrary local port isn't bound by Bridge.
    let free_test_port: SocketAddr = "127.0.0.1:0".parse().unwrap();
    let listener = tokio::net::TcpListener::bind(free_test_port).await;
    assert!(listener.is_ok());

    // Trigger graceful shutdown programmatically
    // We can simulate signal or abort the runner task
    runner_handle.abort();

    // Clean up
    let _ = std::fs::remove_dir_all(&temp_dir);
}

#[tokio::test]
async fn test_proxy_managed_mode_with_concurrent_udp() {
    let temp_dir = std::env::temp_dir().join(format!("bridge-managed-udp-{}", std::process::id()));
    let config_file = temp_dir.join("traefik.yaml");

    // Spawn a mock UDP upstream
    let upstream_socket = tokio::net::UdpSocket::bind("127.0.0.1:0").await.unwrap();
    let upstream_addr = upstream_socket.local_addr().unwrap();

    // Mock UDP echo upstream task
    tokio::spawn(async move {
        let mut buf = [0u8; 1024];
        while let Ok((n, peer)) = upstream_socket.recv_from(&mut buf).await {
            let _ = upstream_socket.send_to(&buf[..n], peer).await;
        }
    });

    let udp_listen_addr: SocketAddr = "127.0.0.1:0".parse().unwrap();
    let udp_proxy_socket = tokio::net::UdpSocket::bind(udp_listen_addr).await.unwrap();
    let actual_listen_port = udp_proxy_socket.local_addr().unwrap().port();
    drop(udp_proxy_socket);

    let udp_service = UdpServiceConfig::new(
        SocketAddr::from(([127, 0, 0, 1], actual_listen_port)),
        upstream_addr,
    );

    let mut proxy_cfg = ProxyConfig::default();
    proxy_cfg.mode = ProxyMode::Managed;
    proxy_cfg.managed = ManagedConfig::new(&config_file);
    proxy_cfg.udp_services = vec![udp_service];

    let registry = Arc::new(DomainRegistry::new());
    registry.insert(
        "remote.test".to_string(),
        Route::new(None, Node::new("vm-02", "10.8.0.2:80".parse().unwrap())),
    );

    let proxy = Arc::new(Proxy::new(Arc::new(proxy_cfg), registry.clone()));

    // Synchronize Traefik dynamic config
    let updated = proxy.sync_managed_provider().expect("sync should succeed");
    assert!(updated);
    assert!(config_file.exists());

    // Spawn proxy run in background
    let proxy_clone = proxy.clone();
    let mut coordinator = ShutdownCoordinator::new(None);
    let run_handle = tokio::spawn(async move {
        proxy_clone.run_with_coordinator(&mut coordinator).await
    });

    // Verify UDP service is running by sending an echo packet
    tokio::time::sleep(Duration::from_millis(100)).await;

    let client = tokio::net::UdpSocket::bind("127.0.0.1:0").await.unwrap();
    client
        .send_to(b"managed-udp-test", SocketAddr::from(([127, 0, 0, 1], actual_listen_port)))
        .await
        .unwrap();

    let mut recv_buf = [0u8; 128];
    let (n, _) = tokio::time::timeout(Duration::from_secs(2), client.recv_from(&mut recv_buf))
        .await
        .expect("timed out waiting for UDP echo")
        .expect("failed to receive UDP response");

    assert_eq!(&recv_buf[..n], b"managed-udp-test");

    run_handle.abort();
    let _ = std::fs::remove_dir_all(&temp_dir);
}

#[test]
fn test_yaml_config_deserialization_with_managed_section() {
    let yaml = r#"
proxy:
  mode: managed
  routing: direct
  managed:
    dynamic_config_path: /tmp/traefik-test.yaml
    local_node_id: vm-01
    entrypoints:
      - web
      - websecure
    tls_enabled: true
    cert_resolver: my-resolver
    default_target_scheme: https
    sync_interval: 10
"#;

    let config = Config::from_yaml_str(yaml).expect("failed to parse yaml with managed config");
    assert_eq!(config.proxy.mode, ProxyMode::Managed);
    assert_eq!(config.proxy.routing, RoutingPreference::Direct);
    assert_eq!(
        config.proxy.managed.dynamic_config_path,
        std::path::PathBuf::from("/tmp/traefik-test.yaml")
    );
    assert_eq!(config.proxy.managed.local_node_id, "vm-01");
    assert_eq!(config.proxy.managed.entrypoints, vec!["web", "websecure"]);
    assert!(config.proxy.managed.tls_enabled);
    assert_eq!(
        config.proxy.managed.cert_resolver.as_deref(),
        Some("my-resolver")
    );
    assert_eq!(config.proxy.managed.default_target_scheme, "https");
    assert_eq!(config.proxy.managed.sync_interval, Duration::from_secs(10));
}

#[test]
fn test_detect_traefik_dynamic_path_coolify_discovery() {
    use bridge::core::config::detect_traefik_dynamic_path_from;

    let temp_dir = std::env::temp_dir().join(format!("bridge-coolify-detect-{}", std::process::id()));
    let coolify_proxy_dir = temp_dir.join("data/coolify/proxy/dynamic");
    let coolify_source_dir = temp_dir.join("data/coolify/source/dynamic");

    // 1. Neither exists -> falls back to /etc/traefik/dynamic/bridge.yaml
    let fallback = detect_traefik_dynamic_path_from(&[&coolify_proxy_dir, &coolify_source_dir]);
    assert_eq!(fallback, std::path::PathBuf::from("/etc/traefik/dynamic/bridge.yaml"));

    // 2. Coolify source exists
    std::fs::create_dir_all(&coolify_source_dir).unwrap();
    let detected_source = detect_traefik_dynamic_path_from(&[&coolify_proxy_dir, &coolify_source_dir]);
    assert_eq!(detected_source, coolify_source_dir.join("bridge.yaml"));

    // 3. Coolify proxy exists (takes priority over source)
    std::fs::create_dir_all(&coolify_proxy_dir).unwrap();
    let detected_proxy = detect_traefik_dynamic_path_from(&[&coolify_proxy_dir, &coolify_source_dir]);
    assert_eq!(detected_proxy, coolify_proxy_dir.join("bridge.yaml"));

    let _ = std::fs::remove_dir_all(&temp_dir);
}


#[test]
fn test_remote_route_resolves_node_target_not_upstream_override() {
    let registry = Arc::new(DomainRegistry::new());
    let node = Node::new("vm-02", "127.0.0.1:8080".parse().unwrap())
        .with_mesh_address("10.8.0.2:8080".parse().unwrap())
        .with_routing(RoutingPreference::Mesh);
    let route = Route::new(Some("127.0.0.1:8080".parse().unwrap()), node);
    registry.insert("api.example.com".to_string(), route);

    let config = ManagedConfig {
        local_node_id: "vm-01".to_string(),
        ..Default::default()
    };
    let generated = proxy::managed::generate_traefik_config(&registry, RoutingPreference::Mesh, &config);
    let url = &generated
        .http
        .services
        .get("bridge-api-example-com")
        .expect("router generated")
        .load_balancer
        .servers[0]
        .url;
    // The 127.0.0.1 upstream is only valid on the origin node; the managed
    // provider must target the remote node's mesh endpoint instead.
    assert_eq!(url, "http://10.8.0.2:8080");
}

#[test]
fn test_internal_node_records_excluded_from_traefik_config() {
    let registry = Arc::new(DomainRegistry::new());
    let node = Node::new("vm-02", "10.8.0.2:443".parse().unwrap())
        .with_mesh_address("10.8.0.2:443".parse().unwrap());
    let route = Route::new(Some("10.8.0.2:443".parse().unwrap()), node);
    registry.insert("vm-02.node.internal".to_string(), route);

    let config = ManagedConfig {
        local_node_id: "vm-01".to_string(),
        ..Default::default()
    };
    let generated = proxy::managed::generate_traefik_config(&registry, RoutingPreference::Mesh, &config);
    assert!(generated.http.routers.is_empty());
    assert!(generated.http.services.is_empty());
}

#[test]
fn test_dashboard_domain_router_generation_in_traefik_config() {
    let registry = Arc::new(DomainRegistry::new());
    let config = ManagedConfig {
        local_node_id: "app-svr-03".to_string(),
        dashboard_domain: Some("bridge-dash.usebantr.site".to_string()),
        dashboard_upstream: Some("http://172.17.0.1:9090".to_string()),
        entrypoints: vec!["websecure".to_string()],
        tls_enabled: true,
        cert_resolver: Some("letsencrypt".to_string()),
        ..Default::default()
    };

    let generated = proxy::managed::generate_traefik_config(&registry, RoutingPreference::Mesh, &config);
    let router_name = "bridge-bridge-dash-usebantr-site";
    let router = generated.http.routers.get(router_name).expect("dashboard router generated");
    assert_eq!(router.rule, "Host(`bridge-dash.usebantr.site`)");
    assert_eq!(router.entry_points, vec!["websecure"]);
    assert!(router.tls.is_some());
    assert_eq!(router.tls.as_ref().unwrap().cert_resolver.as_deref(), Some("letsencrypt"));

    let service = generated.http.services.get(router_name).expect("dashboard service generated");
    assert_eq!(service.load_balancer.servers[0].url, "http://172.17.0.1:9090");
}

