[package]
name = "proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
registry.workspace = true
hyper = { version = "1.11.1", features = ["client", "server","http1", "http2"] }
hyper-util = { version = "0.1", features = ["full"] }
http-body-util = "0.1"
tokio.workspace = true
tracing.workspace = true
serde.workspace = true
smart-default.workspace = true
url.workspace = true
bytes = "1.12.1"
futures = "0.3.34"
crossbeam-deque = "0.8.8"
socket2 = "0.6.5"
serde_json.workspace = true
serde_yaml.workspace = true
